import { PrismaClient } from '@prisma/client';

export async function seedReferral(prisma: PrismaClient) {
    console.log('Seeding general settings...');

    await prisma.referralLevel.createMany({
        data: [
            {
                id: '00000000-0000-0000-0000-000000000001',
                levelName: 'Level1',
                isActive: true,
                createdAt: new Date(),
                createdBy: 'system',
                updatedAt: new Date(),
                updatedBy: 'system',
                deletedAt: null,
                deletedBy: null,
                levelNumber: 1,
                referralBonusPercentage: 5,
            },
            {
                id: '00000000-0000-0000-0000-000000000002',
                levelName: 'Level2',
                isActive: true,
                createdAt: new Date(),
                createdBy: 'system',
                updatedAt: new Date(),
                updatedBy: 'system',
                deletedAt: null,
                deletedBy: null,
                levelNumber: 2,
                referralBonusPercentage: 2,
            },
            {
                id: '00000000-0000-0000-0000-000000000003',
                levelName: 'Level3',
                isActive: true,
                createdAt: new Date(),
                createdBy: 'system',
                updatedAt: new Date(),
                updatedBy: 'system',
                deletedAt: null,
                deletedBy: null,
                levelNumber: 3,
                referralBonusPercentage: 1,
            },
            {
                id: '00000000-0000-0000-0000-000000000004',
                levelName: 'Level4',
                isActive: true,
                createdAt: new Date(),
                createdBy: 'system',
                updatedAt: new Date(),
                updatedBy: 'system',
                deletedAt: null,
                deletedBy: null,
                levelNumber: 4,
                referralBonusPercentage: 1,
            },
            {
                id: '00000000-0000-0000-0000-000000000005',
                levelName: 'Level5',
                isActive: true,
                createdAt: new Date(),
                createdBy: 'system',
                updatedAt: new Date(),
                updatedBy: 'system',
                deletedAt: null,
                deletedBy: null,
                levelNumber: 5,
                referralBonusPercentage: 1,
            },
            {
                id: '00000000-0000-0000-0000-000000000006',
                levelName: 'Level6',
                isActive: true,
                createdAt: new Date(),
                createdBy: 'system',
                updatedAt: new Date(),
                updatedBy: 'system',
                deletedAt: null,
                deletedBy: null,
                levelNumber: 6,
                referralBonusPercentage: 1,
            },
            {
                id: '00000000-0000-0000-0000-000000000007',
                levelName: 'Level7',
                isActive: true,
                createdAt: new Date(),
                createdBy: 'system',
                updatedAt: new Date(),
                updatedBy: 'system',
                deletedAt: null,
                deletedBy: null,
                levelNumber: 7,
                referralBonusPercentage: 1,
            },
            {
                id: '00000000-0000-0000-0000-000000000008',
                levelName: 'Level8',
                isActive: true,
                createdAt: new Date(),
                createdBy: 'system',
                updatedAt: new Date(),
                updatedBy: 'system',
                deletedAt: null,
                deletedBy: null,
                levelNumber: 8,
                referralBonusPercentage: 1,
            },
            {
                id: '00000000-0000-0000-0000-000000000009',
                levelName: 'Level9',
                isActive: true,
                createdAt: new Date(),
                createdBy: 'system',
                updatedAt: new Date(),
                updatedBy: 'system',
                deletedAt: null,
                deletedBy: null,
                levelNumber: 9,
                referralBonusPercentage: 1,
            },
            {
                id: '00000000-0000-0000-0000-000000000010',
                levelName: 'Level10',
                isActive: true,
                createdAt: new Date(),
                createdBy: 'system',
                updatedAt: new Date(),
                updatedBy: 'system',
                deletedAt: null,
                deletedBy: null,
                levelNumber: 10,
                referralBonusPercentage: 1,
            },
            {
                id: '00000000-0000-0000-0000-000000000011',
                levelName: 'Level11',
                isActive: true,
                createdAt: new Date(),
                createdBy: 'system',
                updatedAt: new Date(),
                updatedBy: 'system',
                deletedAt: null,
                deletedBy: null,
                levelNumber: 11,
                referralBonusPercentage: 1,
            },
            {
                id: '00000000-0000-0000-0000-000000000012',
                levelName: 'Level12',
                isActive: true,
                createdAt: new Date(),
                createdBy: 'system',
                updatedAt: new Date(),
                updatedBy: 'system',
                deletedAt: null,
                deletedBy: null,
                levelNumber: 12,
                referralBonusPercentage: 1,
            },
            {
                id: '00000000-0000-0000-0000-000000000013',
                levelName: 'Level13',
                isActive: true,
                createdAt: new Date(),
                createdBy: 'system',
                updatedAt: new Date(),
                updatedBy: 'system',
                deletedAt: null,
                deletedBy: null,
                levelNumber: 13,
                referralBonusPercentage: 1,
            },
            {
                id: '00000000-0000-0000-0000-000000000014',
                levelName: 'Level14',
                isActive: true,
                createdAt: new Date(),
                createdBy: 'system',
                updatedAt: new Date(),
                updatedBy: 'system',
                deletedAt: null,
                deletedBy: null,
                levelNumber: 14,
                referralBonusPercentage: 1,
            },
            {
                id: '00000000-0000-0000-0000-000000000015',
                levelName: 'Level15',
                isActive: true,
                createdAt: new Date(),
                createdBy: 'system',
                updatedAt: new Date(),
                updatedBy: 'system',
                deletedAt: null,
                deletedBy: null,
                levelNumber: 15,
                referralBonusPercentage: 1,
            },
        ]

    });

    //console.log(`Seeded ${settings.length} general settings`);
}







